server:
  port: 18124
spring:
  # RabbitMQ 配置项，对应 RabbitProperties 配置类
  rabbitmq:
    host: 172.31.2.27 # RabbitMQ 服务的地址
    port: 5672 # RabbitMQ 服务的端口
    username: root # RabbitMQ 服务的账号
    password: root # RabbitMQ 服务的密码
    publisher-confirm-type: simple # 设置 Confirm 类型为 SIMPLE 。
    listener:
      simple:
        acknowledge-mode: manual # 配置 Consumer 手动提交 (manual || correlated )

