server:
  port: 18123
spring:
  # RabbitMQ 配置项，对应 RabbitProperties 配置类
  rabbitmq:
    host: 172.31.2.27 # RabbitMQ 服务的地址
    port: 5672 # RabbitMQ 服务的端口
    username: root # RabbitMQ 服务的账号
    password: root # RabbitMQ 服务的密码
#    template:
#      # 对应 RabbitProperties.Retry 类
#      retry:
#        enabled: true # 开启发送机制
#        max-attempts: 3 # 最大重试次数。默认为 3 。
#        initial-interval: 1000 # 重试间隔，单位为毫秒。默认为 1000 。
#    listener:
#      simple:
#        # 对应 RabbitProperties.ListenerRetry 类
         # 并发消费配置 concurrency & max-concurrency
#        concurrency: 2 # 每个 @ListenerContainer 的并发消费的线程数
#        max-concurrency: 10 # 每个 @ListenerContainer 允许的并发消费的线程数
#        retry:
#          enabled: true # 开启消费重试机制
#          max-attempts: 3 # 最大重试次数(包括首次的正常消费)。默认为 3
#          initial-interval: 1000 # 重试间隔，单位为毫秒。默认为 1000 。

